# Generated by Django 2.2.10 on 2020-02-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200221_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionkey',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Customer'),
        ),
    ]
