# Generated by Django 2.2.10 on 2020-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200221_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='msisdn',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
